// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtocol.proto

package com.micolx.connector.protobuf;

public interface AckMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AckMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgID = 1;</code>
   * @return The msgID.
   */
  java.lang.String getMsgID();
  /**
   * <code>string msgID = 1;</code>
   * @return The bytes for msgID.
   */
  com.google.protobuf.ByteString
      getMsgIDBytes();

  /**
   * <code>string recipientID = 2;</code>
   * @return The recipientID.
   */
  java.lang.String getRecipientID();
  /**
   * <code>string recipientID = 2;</code>
   * @return The bytes for recipientID.
   */
  com.google.protobuf.ByteString
      getRecipientIDBytes();

  /**
   * <code>.AckType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.AckType type = 3;</code>
   * @return The type.
   */
  com.micolx.connector.protobuf.AckType getType();
}
