// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtocol.proto

package com.micolx.connector.protobuf;

/**
 * Protobuf type {@code AckMessage}
 */
public final class AckMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AckMessage)
    AckMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AckMessage.newBuilder() to construct.
  private AckMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AckMessage() {
    msgID_ = "";
    recipientID_ = "";
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AckMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AckMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            msgID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            recipientID_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.micolx.connector.protobuf.MessageProtocol.internal_static_AckMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.micolx.connector.protobuf.MessageProtocol.internal_static_AckMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.micolx.connector.protobuf.AckMessage.class, com.micolx.connector.protobuf.AckMessage.Builder.class);
  }

  public static final int MSGID_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgID_;
  /**
   * <code>string msgID = 1;</code>
   * @return The msgID.
   */
  @java.lang.Override
  public java.lang.String getMsgID() {
    java.lang.Object ref = msgID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgID_ = s;
      return s;
    }
  }
  /**
   * <code>string msgID = 1;</code>
   * @return The bytes for msgID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIDBytes() {
    java.lang.Object ref = msgID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECIPIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object recipientID_;
  /**
   * <code>string recipientID = 2;</code>
   * @return The recipientID.
   */
  @java.lang.Override
  public java.lang.String getRecipientID() {
    java.lang.Object ref = recipientID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recipientID_ = s;
      return s;
    }
  }
  /**
   * <code>string recipientID = 2;</code>
   * @return The bytes for recipientID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientIDBytes() {
    java.lang.Object ref = recipientID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recipientID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.AckType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.AckType type = 3;</code>
   * @return The type.
   */
  @java.lang.Override public com.micolx.connector.protobuf.AckType getType() {
    @SuppressWarnings("deprecation")
    com.micolx.connector.protobuf.AckType result = com.micolx.connector.protobuf.AckType.valueOf(type_);
    return result == null ? com.micolx.connector.protobuf.AckType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMsgIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgID_);
    }
    if (!getRecipientIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recipientID_);
    }
    if (type_ != com.micolx.connector.protobuf.AckType.SENT.getNumber()) {
      output.writeEnum(3, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMsgIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgID_);
    }
    if (!getRecipientIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recipientID_);
    }
    if (type_ != com.micolx.connector.protobuf.AckType.SENT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.micolx.connector.protobuf.AckMessage)) {
      return super.equals(obj);
    }
    com.micolx.connector.protobuf.AckMessage other = (com.micolx.connector.protobuf.AckMessage) obj;

    if (!getMsgID()
        .equals(other.getMsgID())) return false;
    if (!getRecipientID()
        .equals(other.getRecipientID())) return false;
    if (type_ != other.type_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgID().hashCode();
    hash = (37 * hash) + RECIPIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getRecipientID().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.micolx.connector.protobuf.AckMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.micolx.connector.protobuf.AckMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.micolx.connector.protobuf.AckMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.micolx.connector.protobuf.AckMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AckMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AckMessage)
      com.micolx.connector.protobuf.AckMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.micolx.connector.protobuf.MessageProtocol.internal_static_AckMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.micolx.connector.protobuf.MessageProtocol.internal_static_AckMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.micolx.connector.protobuf.AckMessage.class, com.micolx.connector.protobuf.AckMessage.Builder.class);
    }

    // Construct using com.micolx.connector.protobuf.AckMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgID_ = "";

      recipientID_ = "";

      type_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.micolx.connector.protobuf.MessageProtocol.internal_static_AckMessage_descriptor;
    }

    @java.lang.Override
    public com.micolx.connector.protobuf.AckMessage getDefaultInstanceForType() {
      return com.micolx.connector.protobuf.AckMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.micolx.connector.protobuf.AckMessage build() {
      com.micolx.connector.protobuf.AckMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.micolx.connector.protobuf.AckMessage buildPartial() {
      com.micolx.connector.protobuf.AckMessage result = new com.micolx.connector.protobuf.AckMessage(this);
      result.msgID_ = msgID_;
      result.recipientID_ = recipientID_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.micolx.connector.protobuf.AckMessage) {
        return mergeFrom((com.micolx.connector.protobuf.AckMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.micolx.connector.protobuf.AckMessage other) {
      if (other == com.micolx.connector.protobuf.AckMessage.getDefaultInstance()) return this;
      if (!other.getMsgID().isEmpty()) {
        msgID_ = other.msgID_;
        onChanged();
      }
      if (!other.getRecipientID().isEmpty()) {
        recipientID_ = other.recipientID_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.micolx.connector.protobuf.AckMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.micolx.connector.protobuf.AckMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object msgID_ = "";
    /**
     * <code>string msgID = 1;</code>
     * @return The msgID.
     */
    public java.lang.String getMsgID() {
      java.lang.Object ref = msgID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgID = 1;</code>
     * @return The bytes for msgID.
     */
    public com.google.protobuf.ByteString
        getMsgIDBytes() {
      java.lang.Object ref = msgID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgID = 1;</code>
     * @param value The msgID to set.
     * @return This builder for chaining.
     */
    public Builder setMsgID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msgID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgID() {
      
      msgID_ = getDefaultInstance().getMsgID();
      onChanged();
      return this;
    }
    /**
     * <code>string msgID = 1;</code>
     * @param value The bytes for msgID to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recipientID_ = "";
    /**
     * <code>string recipientID = 2;</code>
     * @return The recipientID.
     */
    public java.lang.String getRecipientID() {
      java.lang.Object ref = recipientID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipientID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recipientID = 2;</code>
     * @return The bytes for recipientID.
     */
    public com.google.protobuf.ByteString
        getRecipientIDBytes() {
      java.lang.Object ref = recipientID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recipientID = 2;</code>
     * @param value The recipientID to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recipientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string recipientID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientID() {
      
      recipientID_ = getDefaultInstance().getRecipientID();
      onChanged();
      return this;
    }
    /**
     * <code>string recipientID = 2;</code>
     * @param value The bytes for recipientID to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recipientID_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.AckType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.AckType type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.AckType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.micolx.connector.protobuf.AckType getType() {
      @SuppressWarnings("deprecation")
      com.micolx.connector.protobuf.AckType result = com.micolx.connector.protobuf.AckType.valueOf(type_);
      return result == null ? com.micolx.connector.protobuf.AckType.UNRECOGNIZED : result;
    }
    /**
     * <code>.AckType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.micolx.connector.protobuf.AckType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.AckType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AckMessage)
  }

  // @@protoc_insertion_point(class_scope:AckMessage)
  private static final com.micolx.connector.protobuf.AckMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.micolx.connector.protobuf.AckMessage();
  }

  public static com.micolx.connector.protobuf.AckMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AckMessage>
      PARSER = new com.google.protobuf.AbstractParser<AckMessage>() {
    @java.lang.Override
    public AckMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AckMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AckMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AckMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.micolx.connector.protobuf.AckMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

