spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  host: localhost
  port: 6667

zookeeper:
  host: localhost
  port: 2181