// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtocol.proto

package com.example.testclient.protobuf;

public interface GreetMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string time = 3;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
