server:
    error:
        include-message: always
        include-binding-errors: always

zookeeper:
    host: localhost
    port: 2181

spring:
    datasource:
        password:
        url: jdbc:mysql://localhost:3306/pigeon
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
    redis:
        host: localhost
        port: 6379
        password:
        database: 0
    mail:
        host: localhost
        port: 1025
        username: hello
        password: hello
        properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000


